% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:10-Jul-2026 09:43:35

%% Antenna Properties 

antennaObject = design(patchMicrostrip, 1000*1e6);
% Show
figure;
show(antennaObject) 
disp(antennaObject.Length)
disp(antennaObject.Width)

clc;
clear;

initialLength = 0.1439;
initialWidth = 0.18737;

nvars = 2;
lb = [0.13 0.17];
ub = [0.16 0.20];
options=optimoptions('ga','PopulationSize',1000,'MaxGenerations',1000,'Display','iter');
[x,fval] = ga(@fitnessFcn,nvars,[],[],[],[],lb,ub);

fprintf('Initial Length = %.4f m\n',initialLength);
fprintf('Initial Width = %.5f m\n',initialWidth);

fprintf('\nOptimized Length = %.4f m\n',x(1));
fprintf('Optimized Width = %.4f m\n',x(2));

function f = fitnessFcn(x)

Length = x(1);
Width = x(2);

Gain = 8 - 500*(Length-0.148)^2 - 400*(Width-0.190)^2;
Efficiency = 80 - 200*(Length-0.148)^2 - 150*(Width-0.190)^2;

f = -(Gain + Efficiency);

end